INSERT INTO price_list (id, item_name, price_pkr, is_active) VALUES
  (gen_random_uuid()::text, 'ABAYA', 1000.00, true),
  (gen_random_uuid()::text, 'Bag', 1000.00, true),
  (gen_random_uuid()::text, 'Blouse', 1000.00, true),
  (gen_random_uuid()::text, 'BOLERO', 300.00, true),
  (gen_random_uuid()::text, 'BRASIERS', 1000.00, true),
  (gen_random_uuid()::text, 'Capri', 1000.00, true),
  (gen_random_uuid()::text, 'Cardigans', 1500.00, true),
  (gen_random_uuid()::text, 'Dupatta CHIFFON', 1000.00, true),
  (gen_random_uuid()::text, 'Dupatta COTTON', 800.00, true),
  (gen_random_uuid()::text, 'Dupatta EMB', 2000.00, true),
  (gen_random_uuid()::text, 'DUPPATA', 1000.00, true),
  (gen_random_uuid()::text, 'DUSHALAH', 1500.00, true),
  (gen_random_uuid()::text, 'Frock', 1500.00, true),
  (gen_random_uuid()::text, 'FROCK DUPATTA', 2000.00, true),
  (gen_random_uuid()::text, 'GHARARA', 2000.00, true),
  (gen_random_uuid()::text, 'Gharara Set 2pc', 3000.00, true),
  (gen_random_uuid()::text, 'Gharara Set 3pc', 5000.00, true),
  (gen_random_uuid()::text, 'Gown', 2000.00, true),
  (gen_random_uuid()::text, 'JERSER LADIES', 1000.00, true),
  (gen_random_uuid()::text, 'JERSEY LADIES LONG', 1500.00, true),
  (gen_random_uuid()::text, 'JUMP SUIT', 600.00, true),
  (gen_random_uuid()::text, 'JUMPER', 500.00, true),
  (gen_random_uuid()::text, 'Kameez Ladies EMB', 1500.00, true),
  (gen_random_uuid()::text, 'Kameez Ladies FANCY', 2000.00, true),
  (gen_random_uuid()::text, 'Kameez Ladies Plain', 1000.00, true),
  (gen_random_uuid()::text, 'kameez silk', 1500.00, true),
  (gen_random_uuid()::text, 'LADIES GOWN', 2000.00, true),
  (gen_random_uuid()::text, 'LADIES SHALWAR', 800.00, true),
  (gen_random_uuid()::text, 'Ladies Suit 2 Pcs Emb', 800.00, true),
  (gen_random_uuid()::text, 'Ladies Suit 3 Pcs Emb', 2500.00, true),
  (gen_random_uuid()::text, 'Ladies Suit 3 Pcs Plain', 2000.00, true),
  (gen_random_uuid()::text, 'Ladies Suit 4pcs', 4000.00, true),
  (gen_random_uuid()::text, 'LEHENGA', 2000.00, true),
  (gen_random_uuid()::text, 'Lehenga Set 2 Pcs', 5000.00, true),
  (gen_random_uuid()::text, 'Lehenga Set 3 Pcs', 8000.00, true),
  (gen_random_uuid()::text, 'Lehenga Set 4 Pcs', 10000.00, true),
  (gen_random_uuid()::text, 'Lehnga 2 Pcs', 5000.00, true),
  (gen_random_uuid()::text, 'MAXI', 2000.00, true),
  (gen_random_uuid()::text, 'NIGHT SUIT', 1000.00, true),
  (gen_random_uuid()::text, 'Nighty', 2000.00, true),
  (gen_random_uuid()::text, 'Peticot', 800.00, true),
  (gen_random_uuid()::text, 'Pyjama Chooridar', 1000.00, true),
  (gen_random_uuid()::text, 'SAKRAT', 1000.00, true),
  (gen_random_uuid()::text, 'Sarhi 2pc', 2000.00, true),
  (gen_random_uuid()::text, 'Sarhi 3pc', 2500.00, true),
  (gen_random_uuid()::text, 'Sarhi Designer', 1500.00, true),
  (gen_random_uuid()::text, 'Sarhi Heavy work', 2000.00, true),
  (gen_random_uuid()::text, 'Sarhi Light Work', 1000.00, true),
  (gen_random_uuid()::text, 'Sarhi Medium Work', 1500.00, true),
  (gen_random_uuid()::text, 'Sarhi Plain', 1000.00, true),
  (gen_random_uuid()::text, 'Sarhii 2pc Blouse Peticoat', 2000.00, true),
  (gen_random_uuid()::text, 'Scarf', 800.00, true),
  (gen_random_uuid()::text, 'SHAHMEEZ', 800.00, true),
  (gen_random_uuid()::text, 'SHAHRARA', 2000.00, true),
  (gen_random_uuid()::text, 'SHALWAR LADIES', 1000.00, true),
  (gen_random_uuid()::text, 'SHALWAR LILAN', 800.00, true),
  (gen_random_uuid()::text, 'Shalwar silk', 800.00, true),
  (gen_random_uuid()::text, 'SHAMEEZ', 800.00, true),
  (gen_random_uuid()::text, 'SHARARA', 2000.00, true),
  (gen_random_uuid()::text, 'Shawl', 1000.00, true),
  (gen_random_uuid()::text, 'Shawl Pashmina', 1500.00, true),
  (gen_random_uuid()::text, 'Skirt', 1000.00, true),
  (gen_random_uuid()::text, 'Sleeping Suit', 1000.00, true),
  (gen_random_uuid()::text, 'Stoking', 150.00, true),
  (gen_random_uuid()::text, 'STOLL', 800.00, true),
  (gen_random_uuid()::text, 'STOOL', 800.00, true),
  (gen_random_uuid()::text, 'TIGHTS', 600.00, true),
  (gen_random_uuid()::text, 'Top', 800.00, true),
  (gen_random_uuid()::text, 'Uniform Ladies Kt', 1200.00, true),
  (gen_random_uuid()::text, 'Ladies Suit 2 Pc Emb', 2500.00, true),
  (gen_random_uuid()::text, 'APREN', 500.00, true),
  (gen_random_uuid()::text, 'Bath Mat', 500.00, true),
  (gen_random_uuid()::text, 'Bed Cover', 1200.00, true),
  (gen_random_uuid()::text, 'Bed Throw hand woven', 1000.00, true),
  (gen_random_uuid()::text, 'BEDSHEET DOUBLE', 1000.00, true),
  (gen_random_uuid()::text, 'Bedsheet Cotton Double', 1000.00, true),
  (gen_random_uuid()::text, 'Bedsheet Cotton Single', 800.00, true),
  (gen_random_uuid()::text, 'BEDSHEET VELVET', 1500.00, true),
  (gen_random_uuid()::text, 'Blanket Double Bed', 1000.00, true),
  (gen_random_uuid()::text, 'Blanket Single Bed', 900.00, true),
  (gen_random_uuid()::text, 'CAR COVER', 3000.00, true),
  (gen_random_uuid()::text, 'Car interior Alto Mira Cuore', 3000.00, true),
  (gen_random_uuid()::text, 'Car Interior Corrola Civic City Prius', 4500.00, true),
  (gen_random_uuid()::text, 'Car interior Mercedez BMW Crown', 5000.00, true),
  (gen_random_uuid()::text, 'Car interior Prado Cruiser Vigo Range Rover', 6000.00, true),
  (gen_random_uuid()::text, 'Car Interior Swift Vitz', 3500.00, true),
  (gen_random_uuid()::text, 'carpet', 15.00, true),
  (gen_random_uuid()::text, 'Carpet Synthetic square ft', 20.00, true),
  (gen_random_uuid()::text, 'Carpet Woolen square ft', 12.00, true),
  (gen_random_uuid()::text, 'CHADAR', 400.00, true),
  (gen_random_uuid()::text, 'Cook Apron', 150.00, true),
  (gen_random_uuid()::text, 'Curtain Plain Cotton panel', 1500.00, true),
  (gen_random_uuid()::text, 'Curtain With Lining', 400.00, true),
  (gen_random_uuid()::text, 'Curtain Woolen VELVET', 2000.00, true),
  (gen_random_uuid()::text, 'Cushion Covers BIG', 500.00, true),
  (gen_random_uuid()::text, 'Cushions Cover SMALL', 100.00, true),
  (gen_random_uuid()::text, 'CUSION', 500.00, true),
  (gen_random_uuid()::text, 'DARI', 1000.00, true),
  (gen_random_uuid()::text, 'Face Towel', 300.00, true),
  (gen_random_uuid()::text, 'FLAG', 800.00, true),
  (gen_random_uuid()::text, 'Foot Mats', 500.00, true),
  (gen_random_uuid()::text, 'FRILLS', 1000.00, true),
  (gen_random_uuid()::text, 'Gloves 2 Pcs', 200.00, true),
  (gen_random_uuid()::text, 'Handkerchief', 200.00, true),
  (gen_random_uuid()::text, 'KHAIS', 800.00, true),
  (gen_random_uuid()::text, 'MATRESS', 4000.00, true),
  (gen_random_uuid()::text, 'Mattress Cover BIG', 1500.00, true),
  (gen_random_uuid()::text, 'Mattress Cover SMALL', 1000.00, true),
  (gen_random_uuid()::text, 'Napkin', 50.00, true),
  (gen_random_uuid()::text, 'Pillow Covers BIG', 200.00, true),
  (gen_random_uuid()::text, 'Pillow Covers SMALL', 50.00, true),
  (gen_random_uuid()::text, 'PILLOWS', 200.00, true),
  (gen_random_uuid()::text, 'Pullover', 1000.00, true),
  (gen_random_uuid()::text, 'Quilt Cover double', 1200.00, true),
  (gen_random_uuid()::text, 'Quilt Cover single', 1000.00, true),
  (gen_random_uuid()::text, 'Quilt Double', 2000.00, true),
  (gen_random_uuid()::text, 'Quilt Single', 1500.00, true),
  (gen_random_uuid()::text, 'RUG', 10000.00, true),
  (gen_random_uuid()::text, 'RUMAL', 200.00, true),
  (gen_random_uuid()::text, 'SAFA', 400.00, true),
  (gen_random_uuid()::text, 'Seat Cover Foam', 2000.00, true),
  (gen_random_uuid()::text, 'Seat Cover Leather', 2500.00, true),
  (gen_random_uuid()::text, 'Seat Cover Plain', 1500.00, true),
  (gen_random_uuid()::text, 'SOCK 1 PC', 200.00, true),
  (gen_random_uuid()::text, 'Socks 2 Pcs', 200.00, true),
  (gen_random_uuid()::text, 'Sofa Cotton Woolen Seat', 400.00, true),
  (gen_random_uuid()::text, 'Sofa Leather Velvet Suede', 500.00, true),
  (gen_random_uuid()::text, 'Table Cloth', 250.00, true),
  (gen_random_uuid()::text, 'Towel Hand', 100.00, true),
  (gen_random_uuid()::text, 'Towel L', 500.00, true),
  (gen_random_uuid()::text, 'Towel M', 400.00, true),
  (gen_random_uuid()::text, 'WINDOW BLINDS', 200.00, true),
  (gen_random_uuid()::text, 'Bow Tie', 300.00, true),
  (gen_random_uuid()::text, 'CAP', 500.00, true),
  (gen_random_uuid()::text, 'Bush Coat', 600.00, true),
  (gen_random_uuid()::text, 'CAP COTTON', 300.00, true),
  (gen_random_uuid()::text, 'Cap woolen', 500.00, true),
  (gen_random_uuid()::text, 'Chef Coat', 600.00, true),
  (gen_random_uuid()::text, 'Chef Trouser', 600.00, true),
  (gen_random_uuid()::text, 'CHOGHA', 2000.00, true),
  (gen_random_uuid()::text, 'Coat', 1100.00, true),
  (gen_random_uuid()::text, 'COAT DAWN', 1500.00, true),
  (gen_random_uuid()::text, 'Coat School', 1100.00, true),
  (gen_random_uuid()::text, 'DAFFAL CAPE', 1000.00, true),
  (gen_random_uuid()::text, 'Dangree', 1000.00, true),
  (gen_random_uuid()::text, 'Dhoti', 400.00, true),
  (gen_random_uuid()::text, 'Dhusa', 1200.00, true),
  (gen_random_uuid()::text, 'DOWN COAT', 1500.00, true),
  (gen_random_uuid()::text, 'DOWN JACKET', 1500.00, true),
  (gen_random_uuid()::text, 'Hat', 500.00, true),
  (gen_random_uuid()::text, 'Jacket', 1500.00, true),
  (gen_random_uuid()::text, 'Jacket Half', 1000.00, true),
  (gen_random_uuid()::text, 'Jacket Leather', 2500.00, true),
  (gen_random_uuid()::text, 'JACKET REXION', 1500.00, true),
  (gen_random_uuid()::text, 'Jeans', 600.00, true),
  (gen_random_uuid()::text, 'Kameez Boski', 400.00, true),
  (gen_random_uuid()::text, 'Kameez Cotton', 300.00, true),
  (gen_random_uuid()::text, 'kameez karandi', 400.00, true),
  (gen_random_uuid()::text, 'KAMEEZ KHADDAR', 300.00, true),
  (gen_random_uuid()::text, 'KAMEEZ KT', 300.00, true),
  (gen_random_uuid()::text, 'KAMEEZ TROPICAL', 400.00, true),
  (gen_random_uuid()::text, 'Kurta Emboidery', 400.00, true),
  (gen_random_uuid()::text, 'KURTA KHADAR', 300.00, true),
  (gen_random_uuid()::text, 'Kurta Plain', 300.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwa Slik', 650.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwar Boski 2 Pcs', 650.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwar Cotton', 500.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwar Cotton Khaddar 2 Pcs', 550.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwar Karandi', 650.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwar Silk 2pc', 650.00, true),
  (gen_random_uuid()::text, 'Kurta Shalwar Tropical', 650.00, true),
  (gen_random_uuid()::text, 'Kurta Silk', 400.00, true),
  (gen_random_uuid()::text, 'KURTA SIMPL', 400.00, true),
  (gen_random_uuid()::text, 'KURTA SLIK', 400.00, true),
  (gen_random_uuid()::text, 'KURTA TROPICAL', 400.00, true),
  (gen_random_uuid()::text, 'KURTA WOLLEN', 400.00, true),
  (gen_random_uuid()::text, 'Kurts Shalwar Tropical', 650.00, true),
  (gen_random_uuid()::text, 'Long Coat', 2000.00, true),
  (gen_random_uuid()::text, 'LONG JACKET', 2000.00, true),
  (gen_random_uuid()::text, 'Muffler woolen', 400.00, true),
  (gen_random_uuid()::text, 'OVER ALL', 1000.00, true),
  (gen_random_uuid()::text, 'OverCoat', 2000.00, true),
  (gen_random_uuid()::text, 'Pant', 600.00, true),
  (gen_random_uuid()::text, 'PRICE COAT', 1500.00, true),
  (gen_random_uuid()::text, 'PRINCE COAT', 1500.00, true),
  (gen_random_uuid()::text, 'Rain Coat', 1000.00, true),
  (gen_random_uuid()::text, 'SAFARI SHIRT', 350.00, true),
  (gen_random_uuid()::text, 'Safari Suit 2 Pcs', 700.00, true),
  (gen_random_uuid()::text, 'SHALWAR BOSKI', 200.00, true),
  (gen_random_uuid()::text, 'Shalwar Cotton', 250.00, true),
  (gen_random_uuid()::text, 'SHALWAR KARANDI', 200.00, true),
  (gen_random_uuid()::text, 'SHALWAR KT', 150.00, true),
  (gen_random_uuid()::text, 'SHALWAR TROPICAL', 200.00, true),
  (gen_random_uuid()::text, 'Sherwani Embroidery', 2000.00, true),
  (gen_random_uuid()::text, 'Sherwani Plain', 1500.00, true),
  (gen_random_uuid()::text, 'SHIRT BOSKI', 450.00, true),
  (gen_random_uuid()::text, 'Shirt Cotton', 400.00, true),
  (gen_random_uuid()::text, 'Shirt Sattan Silk', 450.00, true),
  (gen_random_uuid()::text, 'SHIRT SATTAN SIMPL', 450.00, true),
  (gen_random_uuid()::text, 'SHIRT SIMPLE', 450.00, true),
  (gen_random_uuid()::text, 'SHIRT TROPICAL', 450.00, true),
  (gen_random_uuid()::text, 'Shirt Woolen', 450.00, true),
  (gen_random_uuid()::text, 'Shorts', 150.00, true),
  (gen_random_uuid()::text, 'Suit 2pc Mens', 1700.00, true),
  (gen_random_uuid()::text, 'Suit 3pc Mens', 2200.00, true),
  (gen_random_uuid()::text, 'Suit Boski 2 Pcs', 700.00, true),
  (gen_random_uuid()::text, 'Suit Cotton 2 Pcs', 500.00, true),
  (gen_random_uuid()::text, 'Suit Karandi 2 Pcs', 700.00, true),
  (gen_random_uuid()::text, 'Suit Khaddar 2 Pcs', 550.00, true),
  (gen_random_uuid()::text, 'Suit Kt 2 Pcs', 500.00, true),
  (gen_random_uuid()::text, 'Suit Ladies 2pc', 2000.00, true),
  (gen_random_uuid()::text, 'Suit Ladies 3pc', 2500.00, true),
  (gen_random_uuid()::text, 'Suit Ladies 4pc', 3500.00, true),
  (gen_random_uuid()::text, 'Suit Linen', 700.00, true),
  (gen_random_uuid()::text, 'SUIT PIECE', 300.00, true),
  (gen_random_uuid()::text, 'Suit Silk 2 Pcs', 700.00, true),
  (gen_random_uuid()::text, 'Suit Silk Stone Wash', 700.00, true),
  (gen_random_uuid()::text, 'Suit Toyobo', 700.00, true),
  (gen_random_uuid()::text, 'Suit Tropical', 700.00, true),
  (gen_random_uuid()::text, 'Suit Tropical Simple', 400.00, true),
  (gen_random_uuid()::text, 'Suit Tropical Woolen', 450.00, true),
  (gen_random_uuid()::text, 'Suit Wassing Wear', 500.00, true),
  (gen_random_uuid()::text, 'Sweat Shirt', 600.00, true),
  (gen_random_uuid()::text, 'Sweat Shirt W CAP', 1000.00, true),
  (gen_random_uuid()::text, 'Sweater FS', 1000.00, true),
  (gen_random_uuid()::text, 'Sweater HS', 700.00, true),
  (gen_random_uuid()::text, 'T', 450.00, true),
  (gen_random_uuid()::text, 'T Shirt', 450.00, true),
  (gen_random_uuid()::text, 'T SHIRT F', 450.00, true),
  (gen_random_uuid()::text, 'T SHIRT POLO', 450.00, true),
  (gen_random_uuid()::text, 'Tie', 300.00, true),
  (gen_random_uuid()::text, 'TRACK SUIT', 1600.00, true),
  (gen_random_uuid()::text, 'Trouser', 600.00, true),
  (gen_random_uuid()::text, 'TSHIRT F', 450.00, true),
  (gen_random_uuid()::text, 'Under Wear', 200.00, true),
  (gen_random_uuid()::text, 'Uniform Army', 1200.00, true),
  (gen_random_uuid()::text, 'Uniform Police', 1200.00, true),
  (gen_random_uuid()::text, 'UPPER', 800.00, true),
  (gen_random_uuid()::text, 'Vest', 200.00, true),
  (gen_random_uuid()::text, 'Waist coat', 700.00, true),
  (gen_random_uuid()::text, 'Suit Boski 2 Pc', 700.00, true),
  (gen_random_uuid()::text, 'Suit Cotton 2 Pc', 500.00, true),
  (gen_random_uuid()::text, 'Suit Tropicals Simple', 700.00, true),
  (gen_random_uuid()::text, 'Suit Tropicals Woolen', 700.00, true),
  (gen_random_uuid()::text, 'Cap Baby', 300.00, true),
  (gen_random_uuid()::text, 'Coat Child', 600.00, true),
  (gen_random_uuid()::text, 'Jacket Baby', 600.00, true),
  (gen_random_uuid()::text, 'KAMEEZ BABY', 400.00, true),
  (gen_random_uuid()::text, 'KURTA CHLID', 80.00, true),
  (gen_random_uuid()::text, 'Lehnga Baby', 1000.00, true),
  (gen_random_uuid()::text, 'Pant child', 400.00, true),
  (gen_random_uuid()::text, 'Romper Baby', 150.00, true),
  (gen_random_uuid()::text, 'Sherwani Child', 600.00, true),
  (gen_random_uuid()::text, 'Sherwani Embroidery Baby', 800.00, true),
  (gen_random_uuid()::text, 'Shirt Baby', 80.00, true),
  (gen_random_uuid()::text, 'Shirt Child', 100.00, true),
  (gen_random_uuid()::text, 'Shorts Baby', 60.00, true),
  (gen_random_uuid()::text, 'Skirt Baby', 120.00, true),
  (gen_random_uuid()::text, 'Stuff toy', 400.00, true),
  (gen_random_uuid()::text, 'Suit 2pc Baby', 800.00, true),
  (gen_random_uuid()::text, 'Sweat Shirt Baby', 150.00, true),
  (gen_random_uuid()::text, 'Sweater Child', 150.00, true),
  (gen_random_uuid()::text, 'Sweater FS Baby', 300.00, true),
  (gen_random_uuid()::text, 'Sweater HS Baby', 150.00, true),
  (gen_random_uuid()::text, 'T Shirt Baby', 100.00, true),
  (gen_random_uuid()::text, 'Top Baby', 150.00, true),
  (gen_random_uuid()::text, 'Trouser Baby', 120.00, true),
  (gen_random_uuid()::text, 'UPPER BABY', 250.00, true)
ON CONFLICT DO NOTHING;
