ALTER TABLE users    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE owners   ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
